# Generated by Django 4.0.4 on 2022-05-04 09:15

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HKUMember',
            fields=[
                ('uid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('LT', 'Lecture Theatre'), ('CR', 'Classroom'), ('TR', 'Tutorial Room')], max_length=2)),
                ('capacity', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('IN', 'Entry'), ('EX', 'Exit')], max_length=2)),
                ('record_datetime', models.DateTimeField()),
                ('member_uid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.hkumember')),
                ('venue_code', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.venue')),
            ],
            options={
                'unique_together': {('member_uid', 'venue_code', 'access_type', 'record_datetime')},
            },
        ),
        migrations.AddField(
            model_name='venue',
            name='members',
            field=models.ManyToManyField(through='api.VisitRecord', to='api.hkumember'),
        ),
    ]
